.TH privbind 1 "22 May 2007" "Privbind 0.1" ""
.SH NAME
privbind \- run a command as an unprivileged user, with additional low
port binding privileges.
.SH SYNOPSIS
.B privbind
\fB\-u\fR \fIuser\fR
[ \fB\-g\fR \fIgroup\fR]
[ \fB\-n\fR \fInum\fR]
\fIcommand\fR [ \fIarguments\fR .\|.\|. ]
.SH DESCRIPTION
Normally in Linux, only a superuser process can bind an Internet domain socket
with a reserved port (port numbers less than 1024). Accordingly,
server processes are typically run with superuser privileges, which can be
dropped after binding the reserved port.
.PP
.B privbind
can run a server, right from the start, under an unprivileged non-root
user with just one extra privilege: the server can bind low ports.
.PP
.B privbind
is useful in several situations. It can be used when the server code cannot
be trusted enough to start it as root; It can be used when the server is
written in a language without the setuid(2) feature (e.g., Java); It
can also be used to run a server written to remain running as root,
while all the privileges it really needs is the ability to bind low ports.
.PP
.SH OPTIONS
.TP
.B \-u
The
.B \-u
option is mandatory, and specifies under which user to run the given command.
The user can be specified using either a username, or a numeric user id.
It should be an unprivileged (non-root) user.
.TP
.B \-g
Specifies the group to switch to when running the given command. If this
option is missing, then the given user's default group is used.
.TP
.BR \-n
.BR privbind 's
default behaviour is to allow the command being run to do privileged binds
as many times as it wishes. In order to do that (see "How it works" below),
the
.B privbind
process needs to continue running (as root) as long as the child program
is running.

The \fB\-n \fInum\fR option tells
.B privbind
that it can assume that only num binds need to be given elevated privileges.
After this number of binds have been done, 
.BR privbind 's
root process will exit, leaving behind only the unprivileged user-specified
program running.
.TP
.BR \-h
Shows a short help screen, and exits.
.SH "EXIT STATUS"
Using technical jargon,
.B privbind
execs \fIcommand\fR as its main process, running itself in the background. The
practical upshot of this, in layman terms, is that the user never gets to see
\fBprivbind\fR's exist status. When running \fBprivbind\fR, the process will exit
whenever, and with whatever exit status, \fIcommand\fR does.

The above point should be particularly noted when using \fBprivbind\fR to run daemons.

.SH "SECURITY CONSIDERATIONS"
\fBprivbind\fR has no SUID parts, and runs within the confines of a single process.
This serves to minimize the security implications of using it. It is highly advised
that \fBprivbind\fR \fInot\fR be made SUID, as this would allow any user that can
run it to run any process as any other (non-root) user. At the moment privbind detects
such a situation and warns about it, but does not outright prevent it.

.SH "BUGS"
\fBprivbind\fR currently uses "SOCK_SEQPACKET" for communication between
privileged and non-privileged processes. This socket type is only, currently,
implemented on relatively new version of Linux, which makes privbind none
portable to other platforms.
.P
\fBprivbind\fR currently has a race condition if a multi-process \fIcommand\fR
calls bind to privileged ports from more than one process simultaneously.
.P
At the moment, certain conditions may result in \fIcommand\fR receiving
signals as a result of actions carried out by \fBprivbind\fR. At the moment,
the only known case is of SIGPIPE when \fBprivbind\fR is run with the \fB-n\fR
option.

.SH "VERSION"
The version of
.B privbind
described by this manual page is 0.2 (June 5, 2007)
.SH "COPYRIGHT"
Copyright (C) 2006-2007, Shachar Shemesh.

.B privbind
was written by Shachar Shemesh, with contributions from Amos Shapira and
Nadav Har'El.

.B privbind
is free software, released under the GNU General Public License (GPL).
See the COPYING file for more information and the exact license terms.

The latest version of this software can be found in

    http://sourceforge.net/projects/privbind
.SH "SEE ALSO"
.BR su (1),
.BR capabilities (7),
.BR bind (2),
.BR setuid (2),
.BR ld.so (8),
.BR unix (7)
